### ISSUE TITLE
Weird character on output

### ISSUE THREAD

**Issue by arknable** [nanovms/ops-intellij#11]
I see this weird character on tool window from cli output.

```
booting /home/arknable/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2021.1.1/e051d885e757b286781f50305504d7b8db3e1dba/ideaIC-2021.1.1/bin/.ops/images/node ...
en1: assigned 10.0.2.15
test
[31mexit status 1[0m
```

looks like color codes

**Comment by arknable** [comment]
@eyberg Please verify

**Comment by eyberg** [comment]
yes those are color codes - i'm ok w/those being left in for now - not sure the console has a way of using them which is ok - we could maybe a no-color switch if necessary but that's low pri

**Comment by arknable** [comment]
I stripped color codes via linked PR for now
