### ISSUE TITLE
ops working but qemu not being found on mac

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-intellij#8]
the new plugin update allowed ops to run but it wasn't finding qemu on my mac

![image](https://user-images.githubusercontent.com/22410/122305188-524e4700-cebb-11eb-8f9d-7397b7ff3061.png)

probably (totally wag) what is going on is that the qemu lookup happens here:

https://github.com/nanovms/ops/blob/master/qemu/hypervisor_unix.go#L12

that PATH env var is set via .zshrc or .bashrc or whatever and for me that means it has /usr/local/bin holding qemu

prob what needs to happen is one of 2 things:

1) call runtime.exe with something like bash -c  "blah"

or

2) populate PATH with whatever is in the env var PATH to begin with and pass that into runtime.exec https://www.programmersought.com/article/1471482626/ <-- this is probably the better way if this works since then you aren't guessing what shell someone is using

**Comment by eyberg** [comment]
looks like $HOME is not being set either which causes  lepton/Homedir to return empty string via https://golang.org/pkg/os/#UserHomeDir  - so should treat it the same as $PATH

**Comment by arknable** [comment]
> looks like $HOME is not being set either which causes lepton/Homedir to return empty string via https://golang.org/pkg/os/#UserHomeDir - so should treat it the same as $PATH

Added by https://github.com/nanovms/ops-intellij/pull/10/commits/7b90a6ea997eb0e4ce3770f073c4a86c44648e81
